// src/pages/estudiantes/EstudianteFormPage.jsx
import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  Box,
  Button,
  Card,
  CardContent,
  FormControlLabel,
  Switch,
  TextField,
  Typography,
  Alert,
  Snackbar,
  CircularProgress,
  MenuItem,
} from '@mui/material';
import SaveIcon from '@mui/icons-material/Save';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import { getEstudiante, createEstudiante, updateEstudiante } from '../../api/estudiantesService';
import { getUsuarios } from '../../api/usuariosService';

const EstudianteFormPage = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const isEditing = Boolean(id);

  const [formData, setFormData] = useState({
    usuarioId: '',
    codigo: '',
    activo: true,
  });
  const [usuarios, setUsuarios] = useState([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [snackbar, setSnackbar] = useState({ open: false, message: '', severity: 'success' });

  useEffect(() => {
    fetchUsuarios();
    if (isEditing) {
      fetchEstudiante();
    }
  }, [id]);

  const fetchUsuarios = async () => {
    try {
      const response = await getUsuarios();
      setUsuarios(response.data);
    } catch (error) {
      console.error('Error al cargar usuarios:', error);
    }
  };

  const fetchEstudiante = async () => {
    setLoading(true);
    try {
      const response = await getEstudiante(id);
      const estudiante = response.data;
      setFormData({
        usuarioId: estudiante.usuarioId || '',
        codigo: estudiante.codigo || '',
        activo: estudiante.activo ?? true,
      });
    } catch (error) {
      console.error('Error al cargar estudiante:', error);
      setSnackbar({
        open: true,
        message: 'Error al cargar los datos del estudiante.',
        severity: 'error',
      });
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSwitchChange = (e) => {
    setFormData((prev) => ({ ...prev, activo: e.target.checked }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.usuarioId || !formData.codigo) {
      setSnackbar({
        open: true,
        message: 'Por favor complete todos los campos obligatorios.',
        severity: 'warning',
      });
      return;
    }

    setSaving(true);
    try {
      const payload = {
        usuarioId: Number(formData.usuarioId),
        codigo: formData.codigo,
        activo: formData.activo,
      };

      if (isEditing) {
        await updateEstudiante(id, payload);
        setSnackbar({
          open: true,
          message: 'Estudiante actualizado correctamente.',
          severity: 'success',
        });
      } else {
        await createEstudiante(payload);
        setSnackbar({
          open: true,
          message: 'Estudiante creado correctamente.',
          severity: 'success',
        });
      }

      setTimeout(() => {
        navigate('/estudiantes');
      }, 1000);
    } catch (error) {
      console.error('Error al guardar estudiante:', error);
      setSnackbar({
        open: true,
        message: isEditing
          ? 'Error al actualizar el estudiante.'
          : 'Error al crear el estudiante.',
        severity: 'error',
      });
    } finally {
      setSaving(false);
    }
  };

  const handleCloseSnackbar = () => {
    setSnackbar((prev) => ({ ...prev, open: false }));
  };

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: 400 }}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3 }}>
      <Box sx={{ display: 'flex', alignItems: 'center', mb: 3, gap: 2 }}>
        <Button
          variant="outlined"
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/estudiantes')}
        >
          Volver
        </Button>
        <Typography variant="h4" component="h1">
          {isEditing ? 'Editar Estudiante' : 'Nuevo Estudiante'}
        </Typography>
      </Box>

      <Card sx={{ maxWidth: 600 }}>
        <CardContent>
          <Box component="form" onSubmit={handleSubmit} sx={{ display: 'flex', flexDirection: 'column', gap: 2.5 }}>
            <TextField
              select
              label="Usuario"
              name="usuarioId"
              value={formData.usuarioId}
              onChange={handleChange}
              required
              fullWidth
            >
              {usuarios.map((usuario) => (
                <MenuItem key={usuario.id} value={usuario.id}>
                  {usuario.nombre}
                </MenuItem>
              ))}
            </TextField>

            <TextField
              label="Codigo"
              name="codigo"
              value={formData.codigo}
              onChange={handleChange}
              required
              fullWidth
            />

            <FormControlLabel
              control={
                <Switch
                  checked={formData.activo}
                  onChange={handleSwitchChange}
                  color="primary"
                />
              }
              label={formData.activo ? 'Activo' : 'Inactivo'}
            />

            <Box sx={{ display: 'flex', gap: 2, mt: 1 }}>
              <Button
                type="submit"
                variant="contained"
                startIcon={<SaveIcon />}
                disabled={saving}
              >
                {saving ? 'Guardando...' : isEditing ? 'Actualizar' : 'Crear'}
              </Button>
              <Button
                variant="outlined"
                color="inherit"
                onClick={() => navigate('/estudiantes')}
                disabled={saving}
              >
                Cancelar
              </Button>
            </Box>
          </Box>
        </CardContent>
      </Card>

      {/* Snackbar para notificaciones */}
      <Snackbar
        open={snackbar.open}
        autoHideDuration={4000}
        onClose={handleCloseSnackbar}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert onClose={handleCloseSnackbar} severity={snackbar.severity} variant="filled">
          {snackbar.message}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default EstudianteFormPage;

// src/views/estudiantes/EstudianteFormPage.vue
<template>
  <AppLayout>
    <div class="estudiante-form-page">
      <!-- Título -->
      <h1 class="text-3xl font-bold mb-4">
        {{ isEditing ? 'Editar Estudiante' : 'Nuevo Estudiante' }}
      </h1>

      <!-- Alertas -->
      <Alert v-if="alert.show" :type="alert.type" :message="alert.message" @close="alert.show = false" />

      <!-- Formulario -->
      <div class="card" style="max-width: 600px;">
        <div class="card-body">
          <form @submit.prevent="handleSubmit">
            <!-- Seleccionar Usuario -->
            <div class="form-group">
              <label for="usuarioId" class="form-label">Usuario *</label>
              <select
                id="usuarioId"
                v-model.number="form.usuarioId"
                class="form-select"
                :class="{ error: errors.usuarioId }"
                :disabled="loadingUsuarios || isEditing"
                required
              >
                <option value="">Selecciona un usuario</option>
                <option v-for="usuario in usuarios" :key="usuario.id" :value="usuario.id">
                  {{ usuario.nombre }} ({{ usuario.correo }})
                </option>
              </select>
              <span v-if="errors.usuarioId" class="form-error">{{ errors.usuarioId }}</span>
              <small class="text-sm" style="color: var(--gray-500);">
                Solo se muestran usuarios con rol ESTUDIANTE
              </small>
            </div>

            <!-- Código -->
            <div class="form-group">
              <label for="codigo" class="form-label">Código del Estudiante *</label>
              <input
                id="codigo"
                v-model="form.codigo"
                type="text"
                class="form-input"
                :class="{ error: errors.codigo }"
                placeholder="EST-2024-001"
                required
              />
              <span v-if="errors.codigo" class="form-error">{{ errors.codigo }}</span>
            </div>

            <!-- Activo -->
            <div class="form-group">
              <label class="flex items-center gap-2">
                <input
                  v-model="form.activo"
                  type="checkbox"
                  style="width: auto;"
                />
                <span class="form-label" style="margin: 0;">Estudiante activo</span>
              </label>
            </div>

            <!-- Botones -->
            <div class="flex gap-2">
              <button
                type="submit"
                class="btn btn-primary"
                :disabled="loading"
              >
                <template v-if="loading">
                  <div class="loader loader-sm" style="border-color: white transparent white transparent;"></div>
                  Guardando...
                </template>
                <template v-else>
                  {{ isEditing ? 'Actualizar' : 'Crear' }} Estudiante
                </template>
              </button>
              <router-link to="/estudiantes" class="btn btn-secondary">
                Cancelar
              </router-link>
            </div>
          </form>
        </div>
      </div>
    </div>
  </AppLayout>
</template>

<script>
import { ref, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { estudiantesService, usuariosService } from '@/api'
import AppLayout from '@/components/AppLayout.vue'
import Alert from '@/components/Alert.vue'

export default {
  name: 'EstudianteFormPage',
  components: {
    AppLayout,
    Alert
  },
  setup() {
    const route = useRoute()
    const router = useRouter()

    const loading = ref(false)
    const loadingUsuarios = ref(true)
    const alert = ref({ show: false, type: 'success', message: '' })

    const isEditing = computed(() => !!route.params.id)

    const form = ref({
      usuarioId: '',
      codigo: '',
      activo: true
    })

    const errors = ref({})
    const usuarios = ref([])

    // Cargar usuarios
    const cargarUsuarios = async () => {
      try {
        loadingUsuarios.value = true
        const allUsuarios = await usuariosService.getAll()
        // Filtrar solo usuarios con rol ESTUDIANTE
        usuarios.value = allUsuarios.filter(u => u.rol === 'ESTUDIANTE')
      } catch (error) {
        console.error('Error al cargar usuarios:', error)
      } finally {
        loadingUsuarios.value = false
      }
    }

    // Cargar datos del estudiante si está editando
    const cargarEstudiante = async () => {
      try {
        loading.value = true
        const estudiante = await estudiantesService.getById(route.params.id)
        form.value = {
          usuarioId: estudiante.usuarioId,
          codigo: estudiante.codigo,
          activo: estudiante.activo
        }
      } catch (error) {
        alert.value = { show: true, type: 'error', message: 'Error al cargar estudiante' }
        console.error(error)
      } finally {
        loading.value = false
      }
    }

    // Validar formulario
    const validarFormulario = () => {
      errors.value = {}
      let isValid = true

      if (!form.value.usuarioId) {
        errors.value.usuarioId = 'Debe seleccionar un usuario'
        isValid = false
      }

      if (!form.value.codigo || form.value.codigo.trim().length < 3) {
        errors.value.codigo = 'El código debe tener al menos 3 caracteres'
        isValid = false
      }

      return isValid
    }

    // Enviar formulario
    const handleSubmit = async () => {
      if (!validarFormulario()) {
        return
      }

      try {
        loading.value = true

        if (isEditing.value) {
          // Actualizar
          await estudiantesService.update(route.params.id, {
            codigo: form.value.codigo,
            activo: form.value.activo
          })
          alert.value = { show: true, type: 'success', message: 'Estudiante actualizado correctamente' }
        } else {
          // Crear
          await estudiantesService.create(form.value)
          alert.value = { show: true, type: 'success', message: 'Estudiante creado correctamente' }
        }

        // Redirigir después de 1 segundo
        setTimeout(() => {
          router.push('/estudiantes')
        }, 1000)
      } catch (error) {
        alert.value = { show: true, type: 'error', message: 'Error al guardar estudiante' }
        console.error(error)
      } finally {
        loading.value = false
      }
    }

    onMounted(() => {
      cargarUsuarios()
      if (isEditing.value) {
        cargarEstudiante()
      }
    })

    return {
      loading,
      loadingUsuarios,
      alert,
      isEditing,
      form,
      errors,
      usuarios,
      handleSubmit
    }
  }
}
</script>
